name: ca_dfatd_sema_sanctions
description: "[OSANC] Canada Special Economic Measures Act Sanctions"
schedule: daily
pipeline:
  init:
    method: seed
    params:
      url: 'http://www.international.gc.ca/sanctions/assets/office_docs/sema-lmes.xml'
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: parse
  parse:
    method: opensanctions.crawlers.ca_dfatd_sema_sanctions:parse
aggregator:
  method: balkhash.memorious:aleph_bulkpush
