name: coe_assembly
description: "[OSANC] Council of Europe Parliamentary Assembly"
schedule: weekly
pipeline:
  init:
    method: opensanctions.crawlers.coe_assembly:parse
    handle:
      pass: store
      page: fetch
  store:
    method: opensanctions.helpers:store_entity
