name: everypolitician
description: "[OSANC] EveryPolitician.org"
schedule: weekly
pipeline:
  init:
    method: seed
    params:
      url: 'https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/countries.json'
    handle:
      pass: fetch_index
  fetch_index:
    method: fetch
    handle:
      pass: index
  index:
    method: opensanctions.crawlers.everypolitician:index
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: parse
  parse:
    method: opensanctions.crawlers.everypolitician:parse
aggregator:
  method: ftm_load_aleph
