name: gb_coh_disqualified
description: "[OSANC] Disqualified company directors from the UK (Companies House)"
schedule: weekly
pipeline:
  init:
    method: seed
    params:
      url: 'https://beta.companieshouse.gov.uk/register-of-disqualifications/A'
    handle:
      pass: fetch_index
  fetch_index:
    method: fetch
    handle:
      pass: alphabetical
  alphabetical:
    method: opensanctions.crawlers.gb_coh_disqualified:alphabetical
    handle:
      pass: fetch_pages
  fetch_pages:
    method: fetch
    handle:
      pass: parse_pages
  parse_pages:
    method: opensanctions.crawlers.gb_coh_disqualified:pages
    handle:
      pass: officer
      url: fetch_pages
  officer:
    method: opensanctions.crawlers.gb_coh_disqualified:officer
    handle:
      pass: store
  # store:
  #   method: opensanctions.helpers:store_entity
  store:
    method: balkhash_emit
    # params:
    #   remote: True
