name: gb_hmt_sanctions
description: "[OSANC] UK HM Treasury sanctions list"
schedule: daily
pipeline:
  init:
    method: seed
    params:
      url: 'https://ofsistorage.blob.core.windows.net/publishlive/ConList.csv'
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: parse
  parse:
    method: opensanctions.crawlers.gb_hmt_sanctions:parse
aggregator:
  method: ftm_load_aleph
