name: kg_fiu_national
description: "[OSANC] Kyrgyz FIU National List"
schedule: weekly
pipeline:
  init:
    method: seed
    params:
      url: 'https://fiu.gov.kg/uploads/59c1fe8b4aae0.xml'
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: parse
  parse:
    method: opensanctions.crawlers.kg_fiu_national:parse
aggregator:
  method: ftm_load_aleph
