name: us_ofac
description: "[OSANC] US OFAC SDN, non-SDN"
schedule: daily
pipeline:
  init:
    method: opensanctions.crawlers.us_ofac:parse
    params:
      urls:
        - 'https://www.treasury.gov/ofac/downloads/sdn.xml'
        - 'https://www.treasury.gov/ofac/downloads/consolidated/consolidated.xml'
    handle:
      pass: store
  store:
    method: opensanctions.helpers:store_entity
