name: us_ofac
description: "[OSANC] US OFAC SDN, non-SDN"
schedule: daily
pipeline:
  init:
    method: seed
    params:
      urls:
        - https://www.treasury.gov/ofac/downloads/sanctions/1.0/sdn_advanced.xml
        - https://www.treasury.gov/ofac/downloads/sanctions/1.0/cons_advanced.xml
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: parse
  parse:
    method: opensanctions.crawlers.us_ofac:parse
    handle:
      pass: store
  # store:
  #   method: opensanctions.helpers:store_entity
  store:
    method: balkhash_emit
    # params:
    #   remote: True
