name: worldbank_debarred
description: "[OSANC] Worldbank List of Debarred Providers"
schedule: weekly
pipeline:
  init:
    method: seed
    params:
      url: 'http://web.worldbank.org/external/default/main?contentMDK=64069844&menuPK=116730&pagePK=64148989&piPK=64148984&querycontentMDK=64069700&theSitePK=84266'
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: parse
  parse:
    method: opensanctions.crawlers.worldbank_debarred:parse
    handle:
      pass: store
  # store:
  #   method: opensanctions.helpers:store_entity
  store:
    method: balkhash_emit
    # params:
    #   remote: True
