name: production

on:
  push:
    branches: [production]
  schedule:
    - cron: "0 3 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: opensanctions
          POSTGRES_PASSWORD: opensanctions
          POSTGRES_DATABASE: opensanctions
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      OPENSANCTIONS_DATABASE_URI: postgresql://opensanctions:opensanctions@localhost/opensanctions

    steps:
      - uses: actions/checkout@v2
        with:
          ref: production
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install -y -qq libicu-dev
          pip install --no-cache-dir -q pyicu awscli
          pip install --no-cache-dir -q -e .
      - name: Fetch cache from data.opensanctions.org
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --no-progress s3://data.opensanctions.org/_cache _cache
      # - name: Restore database
      #   run: |
      #     psql -f _cache/opensanctions.sql $OPENSANCTIONS_DATABASE_URI
      - name: Run opensanctions
        env:
          OPENSANCTIONS_CACHE_PATH: _cache
        run: |
          opensanctions cleanup
          opensanctions --quiet run
      - name: Dump database to file
        run: |
          pg_dump -O -x -c -f _cache/opensanctions.sql $OPENSANCTIONS_DATABASE_URI
      - name: Publish data to data.opensanctions.org
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --delete --no-progress _cache s3://data.opensanctions.org/_cache
          aws s3 sync --delete --no-progress --cache-control "public, max-age=42300" --acl public-read data/datasets s3://data.opensanctions.org/datasets/latest
          aws s3 sync --delete --no-progress --cache-control "public, max-age=84600" --acl public-read data/datasets s3://data.opensanctions.org/datasets/`date +%Y%m%d`
        # aws cloudfront create-invalidation --distribution-id E321O1ATKKHDQT --paths "/datasets/latest/*"
